/**
 * Template-based fallback quiz, used when the offline pack can't be
 * generated by Gemini (no API key, free-tier quota exhausted, network
 * down, etc.). Builds up to 10 simple questions by reading structured
 * fields off the itinerary — no AI required, no network required, no
 * destination-specific copy. The kid still gets text + SFX even when
 * the fancy generator is offline.
 *
 * **Question philosophy** — every template is about one of three
 * things: a real *place* the family is visiting, a real *attraction*
 * (its description, its town, its tag), or a real *Italian word /
 * phrase* the day teaches. Meta-trip filler ("how many stops does
 * this day have?", "what day of the week is day 2?") is intentionally
 * absent — kids tune out instantly on questions about the data
 * structure of their own holiday.
 *
 * Each template:
 *   - takes the day + the rest of the itinerary as input,
 *   - returns a single `QuizQuestion` *only if* it has enough data
 *     to ask a meaningful question (otherwise returns null and the
 *     selector skips it),
 *   - sources its distractors from OTHER attractions / words / towns
 *     in the trip so wrong answers stay plausibly trip-flavored
 *     (the kid is choosing between four real Italian places, not
 *     between Saturnia and Madagascar).
 *
 * The selector then runs all templates, drops the nulls, deduplicates
 * by question text, and trims to the requested count. If we still
 * can't fill the count we just return what we got — the orchestrator
 * treats any non-empty fallback as playable.
 */

import { itinerary } from "../../data/itinerary";
import { attractions, getAttraction } from "../../data/attractions";
import { localizeDay, localizePoi } from "../../data/i18n";
import type {
  AttractionQuizFact,
  Day,
  ItalianWord,
  POI,
  Quiz,
  QuizQuestion
} from "../../data/types";
import type { Lang } from "../lang";
import { QUESTIONS_PER_OFFLINE_PACK } from "./generateQuiz";

const OPTIONS_PER_QUESTION = 4;

/** Per-language micro-dictionary — kept inside the module so the
 *  fallback works without the React `t()` hook (the module runs
 *  inside the orchestrator's startQuiz which is plain logic). Keep
 *  any new copy in sync with `dict.ts` if/when the React UI starts
 *  surfacing it. */
const COPY = {
  en: {
    correct: ["Bravissimo!", "Spot on!", "Nailed it!", "Esatto!", "Mamma mia, yes!"],
    wrong: ["Close one!", "Almost!", "Not quite —", "Oof, nope —", "Ah, the answer is"],
    /** Friendly category labels for attraction tags, used to make
     *  questions like "Which of these is great for water adventures?". */
    tag: {
      water: "splashy water adventures",
      extreme: "thrills and adrenaline",
      nature: "nature walks and forests",
      culture: "old stories and history",
      family: "easy family fun",
      food: "tasting local food",
      view: "breathtaking views",
      cave: "exploring caves",
      village: "wandering an ancient village"
    } as Record<string, string>
  },
  he: {
    correct: ["ברביסימו!", "בדיוק!", "מצוין!", "אֶזָאטוֹ!", "מאמא מיה, כן!"],
    wrong: ["קרוב!", "כמעט!", "לא ממש —", "אופ, לא —", "התשובה היא"],
    tag: {
      water: "הרפתקאות מים מרעננות",
      extreme: "ריגושים ואדרנלין",
      nature: "טבע ויערות",
      culture: "סיפורים והיסטוריה",
      family: "כיף משפחתי קליל",
      food: "טעימות אוכל מקומי",
      view: "נופים עוצרי נשימה",
      cave: "חקר מערות",
      village: "טיול בכפר עתיק"
    } as Record<string, string>
  }
} as const;

function pickReactions(
  lang: Lang,
  rng: () => number
): { reactionCorrect: string; reactionWrong: string } {
  const c = COPY[lang];
  const correct = c.correct[Math.floor(rng() * c.correct.length)];
  const wrong = c.wrong[Math.floor(rng() * c.wrong.length)];
  return { reactionCorrect: correct, reactionWrong: wrong };
}

/** Tiny seeded RNG so the same `(day, lang)` combo always produces
 *  the same fallback quiz — kid replaying gets the same set, no
 *  flicker, no surprises. mulberry32 is good enough for shuffles
 *  and 4-option picks; we don't need cryptographic strength here. */
function mulberry32(seed: number): () => number {
  let s = seed >>> 0;
  return function () {
    s = (s + 0x6d2b79f5) >>> 0;
    let t = s;
    t = Math.imul(t ^ (t >>> 15), t | 1);
    t ^= t + Math.imul(t ^ (t >>> 7), t | 61);
    return ((t ^ (t >>> 14)) >>> 0) / 4294967296;
  };
}

function shuffleInPlace<T>(arr: T[], rng: () => number): T[] {
  for (let i = arr.length - 1; i > 0; i--) {
    const j = Math.floor(rng() * (i + 1));
    [arr[i], arr[j]] = [arr[j], arr[i]];
  }
  return arr;
}

/** Pick `n` distractors from `pool`, skipping anything that matches
 *  `correct` (case-insensitive) and any duplicates. Returns fewer
 *  than `n` if the pool is too small — the template caller treats
 *  that as a "skip me" signal. */
function pickDistractors(
  pool: string[],
  correct: string,
  n: number,
  rng: () => number
): string[] {
  const seen = new Set<string>([correct.trim().toLowerCase()]);
  const candidates: string[] = [];
  for (const raw of pool) {
    const v = raw?.trim();
    if (!v) continue;
    const k = v.toLowerCase();
    if (seen.has(k)) continue;
    seen.add(k);
    candidates.push(v);
  }
  shuffleInPlace(candidates, rng);
  return candidates.slice(0, n);
}

/** Wrap a question + correct answer + distractors into a real
 *  `QuizQuestion`, randomizing the slot the correct option sits in
 *  so the kid can't just tap the same letter every time. Returns
 *  null if we don't have enough distractors to make 4 options. */
function buildQ(opts: {
  lang: Lang;
  question: string;
  correct: string;
  distractors: string[];
  rng: () => number;
}): QuizQuestion | null {
  if (opts.distractors.length < OPTIONS_PER_QUESTION - 1) return null;

  const distractors = opts.distractors.slice(0, OPTIONS_PER_QUESTION - 1);
  const correctSlot = Math.floor(opts.rng() * OPTIONS_PER_QUESTION);
  const options: string[] = [];
  let dIdx = 0;
  for (let i = 0; i < OPTIONS_PER_QUESTION; i++) {
    if (i === correctSlot) {
      options.push(opts.correct);
    } else {
      options.push(distractors[dIdx++]);
    }
  }

  const reactions = pickReactions(opts.lang, opts.rng);
  return {
    question: opts.question,
    options,
    correctIndex: correctSlot,
    reactionCorrect: reactions.reactionCorrect,
    reactionWrong: `${reactions.reactionWrong} ${opts.correct}`
  };
}

/** Pull the town name out of a POI's `address`, e.g.
 *  "Località il Pianello, Bagni di Lucca (LU)" → "Bagni di Lucca",
 *  "Piazza del Duomo, 56126 Pisa (PI)" → "Pisa".
 *  Returns null when the address is missing or the trailing segment
 *  before "(XX)" is a street-level locality (Via / Piazza / Mura /
 *  Loc.) rather than a town — those would mislead the kid. */
function extractTown(address: string | undefined): string | null {
  if (!address) return null;
  const provinceMatch = address.match(/([^,]+?)\s*\([A-Z]{2}\)\s*$/);
  if (!provinceMatch) return null;
  // Strip a leading 4–5-digit Italian postal code, e.g. "56126 Pisa".
  const town = provinceMatch[1].replace(/^\d{4,5}\s+/, "").trim();
  if (!town) return null;
  if (/^(?:Via|Viale|Piazza|Piazzale|Mura|Loc\.|Località|Strada|Vicolo|Corso)\b/i.test(town)) {
    return null;
  }
  return town;
}

/* ------------------------------------------------------------------ */
/* Italian-culture wildcard bank                                       */
/* ------------------------------------------------------------------ */

/** A small bilingual bank of kid-friendly "general Italy" facts —
 *  flag, food, cars, scooters, geography. Used by `tplItalianCulture`
 *  as a controlled wildcard sprinkled into the offline pack so the
 *  deck doesn't feel repetitive on attraction-thin days. The pack is
 *  still primarily about today's attractions; the selector caps how
 *  many of these can fire (see `CULTURE_BUDGET` in `buildFallbackQuiz`).
 *  Keep facts at 8-year-old reading level — no politics, no booze,
 *  no scary detail. */
const ITALIAN_CULTURE_FACTS: Record<Lang, AttractionQuizFact[]> = {
  en: [
    {
      question: "What three colours are on the Italian flag, from left to right?",
      correctAnswer: "Green, white, and red",
      distractors: [
        "Red, white, and blue",
        "Yellow, black, and white",
        "Blue, white, and red"
      ]
    },
    {
      question: "Pizza Margherita is named after a real Italian queen and shows off the Italian flag colours. What are the three classic toppings?",
      correctAnswer: "Tomato (red), mozzarella (white) and basil (green)",
      distractors: [
        "Pineapple, ham and corn",
        "Mushrooms, olives and pepperoni",
        "Sweetcorn, egg and broccoli"
      ]
    },
    {
      question: "Which of these famous foods is NOT actually from Italy?",
      correctAnswer: "Spaghetti with meatballs (it's American!)",
      distractors: [
        "Pizza Margherita",
        "Gelato (ice cream)",
        "Lasagna"
      ]
    },
    {
      question: "Italy shares its northern border with a few other countries. Which of these countries does NOT border Italy?",
      correctAnswer: "Spain",
      distractors: [
        "France",
        "Switzerland",
        "Austria"
      ]
    },
    {
      question: "About 2000 years ago, a powerful empire ruled Italy and much of the world. What were the people of this empire called?",
      correctAnswer: "The Romans",
      distractors: [
        "The Greeks",
        "The Egyptians",
        "The Vikings"
      ]
    },
    {
      question: "The Teenage Mutant Ninja Turtles are named after four famous Italian Renaissance artists. Who are they?",
      correctAnswer: "Leonardo, Michelangelo, Donatello, and Raphael",
      distractors: [
        "Mario, Luigi, Toad, and Bowser",
        "Romeo, Juliet, Hamlet, and Othello",
        "Vivaldi, Puccini, Verdi, and Rossini"
      ]
    },
    {
      question: "Who painted the world's most famous painting, the Mona Lisa?",
      correctAnswer: "Leonardo da Vinci, an Italian artist",
      distractors: [
        "Pablo Picasso",
        "Vincent van Gogh",
        "Michelangelo"
      ]
    },
    {
      question: "The main international airport in Rome is named after which famous Italian inventor and artist?",
      correctAnswer: "Leonardo da Vinci",
      distractors: [
        "Julius Caesar",
        "Marco Polo",
        "Christopher Columbus"
      ]
    },
    {
      question: "Italy is shaped a bit like which everyday object?",
      correctAnswer: "A boot",
      distractors: ["A hat", "A spoon", "A football"]
    },
    {
      question: "What is the capital city of Italy?",
      correctAnswer: "Rome",
      distractors: ["Milan", "Florence", "Venice"]
    },
    {
      question: "What is the name of the famous little Italian scooter, designed in the 1940s?",
      correctAnswer: "The Vespa (Italian for 'wasp')",
      distractors: ["The Avocado", "The Tarantula", "The Spaghetti"]
    },
    {
      question: "Ferrari and Lamborghini are both world-famous Italian makers of what?",
      correctAnswer: "Fast sports cars",
      distractors: ["Fizzy lemonade", "Wooden toys", "Pencils and pens"]
    },
    {
      question: "What does the Italian word 'gelato' mean in English?",
      correctAnswer: "Ice cream",
      distractors: ["A small boat", "A song", "A train"]
    },
    {
      question: "In 2014, the Israeli basketball team Maccabi Tel Aviv won the European Championship. In which Italian city did they play the final?",
      correctAnswer: "Milan",
      distractors: ["Rome", "Venice", "Florence"]
    },
    {
      question: "Italy has the most active volcano in Europe. What is its name?",
      correctAnswer: "Mount Etna (in Sicily)",
      distractors: ["Mount Everest", "Mount Fuji", "Mount Kilimanjaro"]
    },
    {
      question: "Which of these is a famous big city in Tuscany?",
      correctAnswer: "Florence",
      distractors: ["Rome", "Venice", "Naples"]
    },
    {
      question: "Tuscany is famous for its beautiful countryside. What does it look like?",
      correctAnswer: "Rolling green hills with vineyards and cypress trees",
      distractors: [
        "Flat sandy deserts with cactus",
        "Snowy mountains with pine trees",
        "Deep jungles with monkeys"
      ]
    },
    {
      question: "In the Maremma area of Tuscany, you can find 'Butteri'. What are they?",
      correctAnswer: "Italian cowboys who ride horses",
      distractors: [
        "A type of creamy butter",
        "People who make pizza",
        "Little green frogs"
      ]
    },
    {
      question: "What type of thick, hand-rolled pasta is super famous in Tuscany?",
      correctAnswer: "Pici",
      distractors: ["Spaghetti", "Macaroni", "Ravioli"]
    },
    {
      question: "Tuscan bread is famous for missing one important ingredient. What is it?",
      correctAnswer: "Salt (it's completely unsalted!)",
      distractors: ["Flour", "Water", "Yeast"]
    },
    {
      question: "For which famous Italian soccer team did Cristiano Ronaldo play?",
      correctAnswer: "Juventus",
      distractors: ["AC Milan", "Inter Milan", "AS Roma"]
    },
    {
      question: "Which Italian rock band won the Eurovision Song Contest in 2021?",
      correctAnswer: "Måneskin",
      distractors: ["ABBA", "The Beatles", "Coldplay"]
    },
    {
      question: "Italy has won the World Cup four times! Which of these is a famous Italian soccer team?",
      correctAnswer: "Juventus",
      distractors: ["Real Madrid", "Manchester United", "Bayern Munich"]
    }
  ],
  he: [
    {
      question: "אילו שלושה צבעים יש בדגל האיטלקי, משמאל לימין?",
      correctAnswer: "ירוק, לבן ואדום",
      distractors: ["אדום, לבן וכחול", "צהוב, שחור ולבן", "כחול, לבן ואדום"]
    },
    {
      question: "פיצה מרגריטה נקראת על שם מלכה איטלקית אמיתית, ומציגה את צבעי הדגל האיטלקי. מה שלוש התוספות הקלאסיות?",
      correctAnswer: "עגבנייה (אדום), מוצרלה (לבן) ובזיליקום (ירוק)",
      distractors: [
        "אננס, אגוזים ותירס",
        "פטריות, זיתים ופפרוני",
        "תירס מתוק, ביצה וברוקולי"
      ]
    },
    {
      question: "איזה מהמאכלים המפורסמים האלה לא באמת הומצא באיטליה?",
      correctAnswer: "ספגטי עם כדורי בשר (זה אמריקאי!)",
      distractors: [
        "פיצה מרגריטה",
        "גלידה (ג'לאטו)",
        "לזניה"
      ]
    },
    {
      question: "איטליה חולקת את הגבול הצפוני שלה עם כמה מדינות. איזו מהמדינות האלה לא גובלת באיטליה?",
      correctAnswer: "ספרד",
      distractors: [
        "צרפת",
        "שווייץ",
        "אוסטריה"
      ]
    },
    {
      question: "לפני כ-2000 שנה, אימפריה חזקה שלטה באיטליה ובחלק גדול מהעולם. איך קראו לאנשי האימפריה הזו?",
      correctAnswer: "הרומאים",
      distractors: [
        "היוונים",
        "המצרים",
        "הוויקינגים"
      ]
    },
    {
      question: "צבי הנינג׳ה נקראים על שם ארבעה אמנים איטלקים מפורסמים מתקופת הרנסנס. מי הם?",
      correctAnswer: "לאונרדו, מיכלאנג׳לו, דונטלו ורפאל",
      distractors: [
        "מריו, לואיג׳י, טואד ובאוזר",
        "רומיאו, יוליה, המלט ואותלו",
        "ויוואלדי, פוצ׳יני, ורדי ורוסיני"
      ]
    },
    {
      question: "מי צייר את הציור המפורסם בעולם, המונה ליזה?",
      correctAnswer: "לאונרדו דה וינצ׳י, אמן איטלקי",
      distractors: [
        "פבלו פיקאסו",
        "וינסנט ואן גוך",
        "מיכלאנג׳לו"
      ]
    },
    {
      question: "נמל התעופה הבינלאומי המרכזי של רומא נקרא על שם איזה ממציא ואמן איטלקי מפורסם?",
      correctAnswer: "לאונרדו דה וינצ׳י",
      distractors: [
        "יוליוס קיסר",
        "מרקו פולו",
        "כריסטופר קולומבוס"
      ]
    },
    {
      question: "צורת איטליה דומה קצת לאיזה חפץ יומיומי?",
      correctAnswer: "מגף",
      distractors: ["כובע", "כף", "כדורגל"]
    },
    {
      question: "מהי בירת איטליה?",
      correctAnswer: "רומא",
      distractors: ["מילאנו", "פירנצה", "ונציה"]
    },
    {
      question: "מה השם של הקטנוע הקטן והמפורסם של איטליה, שעוצב בשנות הארבעים?",
      correctAnswer: "ה־וֶספַּה (׳צרעה׳ באיטלקית)",
      distractors: ["ה־אבוקדו", "ה־טרנטולה", "ה־ספגטי"]
    },
    {
      question: "פרארי ולמבורגיני הם שני יצרנים איטלקיים מפורסמים בעולם של מה?",
      correctAnswer: "מכוניות ספורט מהירות",
      distractors: ["לימונדה תוססת", "צעצועי עץ", "עפרונות ועטים"]
    },
    {
      question: "מה משמעות המילה האיטלקית ׳ג׳לאטו׳ בעברית?",
      correctAnswer: "גלידה",
      distractors: ["סירה קטנה", "שיר", "רכבת"]
    },
    {
      question: "בשנת 2014, מכבי תל אביב בכדורסל זכתה באליפות אירופה. באיזו עיר איטלקית נערך משחק הגמר?",
      correctAnswer: "מילאנו",
      distractors: ["רומא", "ונציה", "פירנצה"]
    },
    {
      question: "באיטליה נמצא הוולקן הפעיל ביותר באירופה. מה שמו?",
      correctAnswer: "הר האטנה (בסיציליה)",
      distractors: ["הר אוורסט", "הר פוג׳י", "הר קילימנג׳רו"]
    },
    {
      question: "איזו מבין אלו היא עיר גדולה ומפורסמת בטוסקנה?",
      correctAnswer: "פירנצה",
      distractors: ["רומא", "ונציה", "נאפולי"]
    },
    {
      question: "טוסקנה מפורסמת באזורי הכפר היפים שלה. איך הם נראים?",
      correctAnswer: "גבעות ירוקות מתגלגלות עם כרמים ועצי ברוש",
      distractors: [
        "מדבריות חול שטוחים עם קקטוסים",
        "הרים מושלגים עם עצי אורן",
        "ג'ונגלים עמוקים עם קופים"
      ]
    },
    {
      question: "באזור המארמה בטוסקנה, אפשר למצוא 'בוּטֶרִי'. מה הם?",
      correctAnswer: "קאובויס איטלקים שרוכבים על סוסים",
      distractors: [
        "סוג של חמאה רכה",
        "אנשים שמכינים פיצה",
        "צפרדעים ירוקות קטנות"
      ]
    },
    {
      question: "איזה סוג של פסטה עבה המגולגלת ביד מפורסמת מאוד בטוסקנה?",
      correctAnswer: "פיצ'י",
      distractors: ["ספגטי", "מקרוני", "רביולי"]
    },
    {
      question: "הלחם הטוסקני מפורסם בגלל שחסר בו מרכיב אחד חשוב. מהו?",
      correctAnswer: "מלח (הוא לגמרי ללא מלח!)",
      distractors: ["קמח", "מים", "שמרים"]
    },
    {
      question: "באיזו קבוצת כדורגל איטלקית מפורסמת שיחק כריסטיאנו רונאלדו?",
      correctAnswer: "יובנטוס",
      distractors: ["מילאן", "אינטר", "רומא"]
    },
    {
      question: "איזו להקת רוק איטלקית זכתה באירוויזיון בשנת 2021?",
      correctAnswer: "מונסקין",
      distractors: ["אבבא", "הביטלס", "קולדפליי"]
    },
    {
      question: "איטליה זכתה במונדיאל ארבע פעמים! איזו מבין אלו היא קבוצת כדורגל איטלקית מפורסמת?",
      correctAnswer: "יובנטוס",
      distractors: ["ריאל מדריד", "מנצ'סטר יונייטד", "באיירן מינכן"]
    }
  ]
};

/* ------------------------------------------------------------------ */
/* Templates — ALL substantive (places / attractions / Italian)        */
/* ------------------------------------------------------------------ */

interface TemplateContext {
  lang: Lang;
  rng: () => number;
  day: Day;
  /** Other days, already localized. */
  otherDays: Day[];
  /** All attractions, already localized — used as a wide distractor
   *  pool. */
  allAttractions: POI[];
  /** Just the attractions the family visits *today*, localized.
   *  Templates use this for the "correct" answer when the question
   *  is grounded in the day's plan. */
  todaysAttractions: POI[];
}

/** Q: what does the Italian word X mean? */
function tplWordMeaning(ctx: TemplateContext): QuizQuestion | null {
  const { day, otherDays, lang, rng } = ctx;
  const words: ItalianWord[] = day.italianWords ?? [];
  if (words.length === 0) return null;
  const w = words[Math.floor(rng() * words.length)];
  if (!w?.meaning) return null;
  const otherMeanings = otherDays
    .flatMap(d => (d.italianWords ?? []).map(o => o.meaning))
    .filter(Boolean);
  const distractors = pickDistractors(
    otherMeanings,
    w.meaning,
    OPTIONS_PER_QUESTION - 1,
    rng
  );
  return buildQ({
    lang,
    question:
      lang === "he"
        ? `מה המשמעות של המילה האיטלקית "${w.word}"?`
        : `What does the Italian word "${w.word}" mean?`,
    correct: w.meaning,
    distractors,
    rng
  });
}

/** Q: how do you say [meaning] in Italian? — reverse of tplWordMeaning. */
function tplWordReverse(ctx: TemplateContext): QuizQuestion | null {
  const { day, otherDays, lang, rng } = ctx;
  const words: ItalianWord[] = day.italianWords ?? [];
  if (words.length === 0) return null;
  const w = words[Math.floor(rng() * words.length)];
  if (!w?.word || !w?.meaning) return null;
  const otherWords = otherDays
    .flatMap(d => (d.italianWords ?? []).map(o => o.word))
    .filter(Boolean);
  const distractors = pickDistractors(
    otherWords,
    w.word,
    OPTIONS_PER_QUESTION - 1,
    rng
  );
  return buildQ({
    lang,
    question:
      lang === "he"
        ? `איך אומרים "${w.meaning}" באיטלקית?`
        : `How do you say "${w.meaning}" in Italian?`,
    correct: w.word,
    distractors,
    rng
  });
}

/** Q: which Italian phrase means "[example translation]"? */
function tplPhraseExample(ctx: TemplateContext): QuizQuestion | null {
  const { day, otherDays, lang, rng } = ctx;
  const phrases = (day.italianWords ?? []).filter(
    w => w.example && w.exampleMeaning
  );
  if (phrases.length === 0) return null;
  const w = phrases[Math.floor(rng() * phrases.length)];
  if (!w.example || !w.exampleMeaning) return null;
  const otherExamples = otherDays
    .flatMap(d => (d.italianWords ?? []).map(o => o.example).filter(Boolean))
    .filter((e): e is string => Boolean(e) && e !== w.example);
  const distractors = pickDistractors(
    otherExamples,
    w.example,
    OPTIONS_PER_QUESTION - 1,
    rng
  );
  return buildQ({
    lang,
    question:
      lang === "he"
        ? `איזה משפט באיטלקית אומר "${w.exampleMeaning}"?`
        : `Which Italian phrase means "${w.exampleMeaning}"?`,
    correct: w.example,
    distractors,
    rng
  });
}

/** Q: a kid-friendly general "Italy" fact pulled from the
 *  `ITALIAN_CULTURE_FACTS` bank above (flag colours, pizza
 *  Margherita, Vespa, Ferrari, gelato, Italy-shaped-like-a-boot,
 *  …). The selector caps how many of these are allowed per pack
 *  (see `CULTURE_BUDGET`) — the deck stays primarily about the
 *  day's actual attractions, with one or two of these sprinkled
 *  in for variety on attraction-thin days. */
function tplItalianCulture(ctx: TemplateContext): QuizQuestion | null {
  const { lang, rng } = ctx;
  const bank = ITALIAN_CULTURE_FACTS[lang];
  if (!bank || bank.length === 0) return null;
  const fact = bank[Math.floor(rng() * bank.length)];
  return buildQ({
    lang,
    question: fact.question,
    correct: fact.correctAnswer,
    distractors: fact.distractors,
    rng
  });
}

/** Q: a hand-curated story / legend / signature-detail question
 *  about an attraction the family visits today. Pulls from the
 *  attraction's `quizFacts` array (authored alongside its
 *  description in `attractions.ts` + the HE overlay) — the
 *  template doesn't generate the question from text, it just lifts
 *  the curated fact and randomizes which option the correct answer
 *  lands in. This is the template that gets us the "Devil's Bridge
 *  → dog" class of question, and it's deliberately FIRST in the
 *  template list so it dominates the offline pack on any day with
 *  story-rich attractions. */
function tplAttractionStory(ctx: TemplateContext): QuizQuestion | null {
  const { todaysAttractions, lang, rng } = ctx;
  // Build a flat (attraction, fact) catalog so we pick uniformly
  // across facts, not across attractions — otherwise an attraction
  // with 4 facts gets the same chance as one with 1 fact and we
  // end up overweighting the latter on multi-pass runs.
  type Pair = { att: POI; fact: AttractionQuizFact };
  const catalog: Pair[] = [];
  for (const att of todaysAttractions) {
    if (!att.quizFacts) continue;
    for (const fact of att.quizFacts) {
      if (!fact.question || !fact.correctAnswer) continue;
      if (!fact.distractors || fact.distractors.length < OPTIONS_PER_QUESTION - 1) continue;
      catalog.push({ att, fact });
    }
  }
  if (catalog.length === 0) return null;

  const pick = catalog[Math.floor(rng() * catalog.length)];
  // Distractor pool: the curated wrong answers from the SAME fact.
  // We don't blend in distractors from other facts because the
  // author already tuned these to be plausible-but-clearly-wrong
  // for THIS specific question (e.g. "A dog" vs "A cat / goat /
  // chicken" — mixing in "Saturnia" would obviously give it away).
  return buildQ({
    lang,
    question: pick.fact.question,
    correct: pick.fact.correctAnswer,
    distractors: pick.fact.distractors,
    rng
  });
}

/** Q: which place is described as "[short description]"? Picks a
 *  real attraction the family visits today, asks the kid to identify
 *  it from its short description. */
function tplAttractionDescription(ctx: TemplateContext): QuizQuestion | null {
  const { todaysAttractions, allAttractions, lang, rng } = ctx;
  const candidates = todaysAttractions.filter(a => a.shortDescription);
  if (candidates.length === 0) return null;
  const a = candidates[Math.floor(rng() * candidates.length)];
  if (!a.shortDescription) return null;
  const distractors = pickDistractors(
    allAttractions.map(o => o.name),
    a.name,
    OPTIONS_PER_QUESTION - 1,
    rng
  );
  return buildQ({
    lang,
    question:
      lang === "he"
        ? `איזה מקום מתואר כך: "${a.shortDescription}"?`
        : `Which place is described as: "${a.shortDescription}"?`,
    correct: a.name,
    distractors,
    rng
  });
}

/** Q: in which town is [attraction] located? Uses the address field. */
function tplAttractionTown(ctx: TemplateContext): QuizQuestion | null {
  const { todaysAttractions, allAttractions, lang, rng } = ctx;
  // Pair every today-attraction with its extracted town; skip ones
  // whose addresses are too messy to extract a real town from.
  const pairs = todaysAttractions
    .map(a => ({ name: a.name, town: extractTown(a.address) }))
    .filter((p): p is { name: string; town: string } => Boolean(p.town));
  if (pairs.length === 0) return null;
  const pick = pairs[Math.floor(rng() * pairs.length)];
  // Distractor towns from the WHOLE itinerary's attractions so the
  // kid is choosing between real Tuscan places, not random words.
  const otherTowns = allAttractions
    .map(a => extractTown(a.address))
    .filter((t): t is string => Boolean(t) && t !== pick.town);
  const distractors = pickDistractors(otherTowns, pick.town, OPTIONS_PER_QUESTION - 1, rng);
  return buildQ({
    lang,
    question:
      lang === "he"
        ? `באיזו עיר נמצא ${pick.name}?`
        : `Which town is ${pick.name} in?`,
    correct: pick.town,
    distractors,
    rng
  });
}

/** Q: which of these places is great for [tag-flavored activity]?
 *  Picks an attraction we visit today that has a tag, asks the kid
 *  to find it; distractors are attractions WITHOUT that tag, so the
 *  question is genuinely answerable from what each place is about. */
function tplAttractionByTag(ctx: TemplateContext): QuizQuestion | null {
  const { todaysAttractions, allAttractions, lang, rng } = ctx;
  const tagCopy = COPY[lang].tag;
  const tagged = todaysAttractions.filter(a => (a.tags ?? []).some(t => tagCopy[t]));
  if (tagged.length === 0) return null;
  const a = tagged[Math.floor(rng() * tagged.length)];
  const tag = (a.tags ?? []).find(t => tagCopy[t]);
  if (!tag) return null;
  const tagLabel = tagCopy[tag];

  // Distractors: attractions across the whole trip that DO NOT have
  // this tag (so the answer is uniquely correct).
  const distractorPool = allAttractions
    .filter(o => o.id !== a.id && !(o.tags ?? []).includes(tag))
    .map(o => o.name);
  const distractors = pickDistractors(distractorPool, a.name, OPTIONS_PER_QUESTION - 1, rng);
  return buildQ({
    lang,
    question:
      lang === "he"
        ? `איזה מהמקומות האלה הוא הכי מתאים ל${tagLabel}?`
        : `Which of these places is the best one for ${tagLabel}?`,
    correct: a.name,
    distractors,
    rng
  });
}

/** Q: which of these places is in the same area as [today's place]?
 *  Tests whether the kid is paying attention to the regional rhythm
 *  of the trip — north vs south. Uses POI.region (data-driven), not
 *  the day-level region (meta). */
function tplAttractionRegion(ctx: TemplateContext): QuizQuestion | null {
  const { todaysAttractions, allAttractions, lang, rng } = ctx;
  if (todaysAttractions.length === 0) return null;
  const today = todaysAttractions[Math.floor(rng() * todaysAttractions.length)];
  const sameRegion = allAttractions.filter(
    a => a.region === today.region && a.id !== today.id
  );
  if (sameRegion.length === 0) return null;
  const correct = sameRegion[Math.floor(rng() * sameRegion.length)].name;
  // Distractors: attractions in a DIFFERENT region from today's, so
  // the answer is uniquely correct on geography.
  const distractorPool = allAttractions
    .filter(a => a.region !== today.region)
    .map(a => a.name);
  const distractors = pickDistractors(distractorPool, correct, OPTIONS_PER_QUESTION - 1, rng);
  return buildQ({
    lang,
    question:
      lang === "he"
        ? `איזה מקום נמצא באותו אזור כמו ${today.name}?`
        : `Which of these places is in the same area as ${today.name}?`,
    correct,
    distractors,
    rng
  });
}

const WORD_TEMPLATES: Array<(ctx: TemplateContext) => QuizQuestion | null> = [
  tplWordMeaning,
  tplWordReverse,
  tplPhraseExample
];

const TEMPLATES: Array<(ctx: TemplateContext) => QuizQuestion | null> = [
  // Curated story trivia first — when the attraction author has
  // written quizFacts for today's stops, these are the highest-
  // quality questions in the deck.
  tplAttractionStory,
  tplAttractionDescription,
  tplAttractionTown,
  tplAttractionByTag,
  tplAttractionRegion
];

/* ------------------------------------------------------------------ */
/* Public entry point                                                  */
/* ------------------------------------------------------------------ */

/**
 * Build a fallback `Quiz` of up to `count` questions for `(day, lang)`,
 * deterministic per `(day, lang, count)`. Throws only if there is no
 * itinerary entry for the day at all (the orchestrator surfaces that
 * as a real error). If templates can't fill the requested count, the
 * returned quiz is shorter — the orchestrator treats any non-empty
 * fallback as playable.
 *
 * Each template can fire MULTIPLE times in one quiz (we re-run the
 * same set in shuffled order after the first pass, picking different
 * source items via the RNG) so a 10-question pack genuinely covers
 * 10 facts about the day instead of the 9 we'd get from one-shot
 * templates.
 */
export function buildFallbackQuiz(
  dayNumber: number,
  lang: Lang,
  count: number = QUESTIONS_PER_OFFLINE_PACK
): Quiz {
  const rawDay = itinerary.find(d => d.dayNumber === dayNumber);
  if (!rawDay) {
    throw new Error(`No itinerary entry for day ${dayNumber}`);
  }

  const day = lang === "he" ? localizeDay(rawDay, "he") : rawDay;
  const otherDays = itinerary
    .filter(d => d.dayNumber !== dayNumber)
    .map(d => (lang === "he" ? localizeDay(d, "he") : d));

  const pastDays = itinerary.filter(d => d.dayNumber <= dayNumber);
  const pastAttractionIds = new Set(
    pastDays.flatMap(d => d.activities.map(a => a.attractionId).filter(Boolean))
  );

  const allAttractions = attractions
    .filter(a => pastAttractionIds.has(a.id))
    .map(a => (lang === "he" ? localizePoi(a, "he") : a));

  // Today's attractions: pull every activity with an `attractionId`
  // and look it up. This gives us proper rich POIs (with shortDesc,
  // tags, address) instead of the bare activity titles, which is
  // what makes the questions actually about *places*.
  const todaysAttractions: POI[] = day.activities
    .map(a => (a.attractionId ? getAttraction(a.attractionId) : null))
    .filter((a): a is POI => Boolean(a))
    .map(a => (lang === "he" ? localizePoi(a, "he") : a));

  // Seed: day + lang + count. Picks a stable but unique RNG stream
  // for each combination.
  const seed = dayNumber * 1009 + (lang === "he" ? 7 : 13) + count * 31;
  const rng = mulberry32(seed);

  const ctx: TemplateContext = {
    lang,
    rng,
    day,
    otherDays,
    allAttractions,
    todaysAttractions
  };

  const collected: QuizQuestion[] = [];
  const seen = new Set<string>();
  const tryAdd = (q: QuizQuestion | null) => {
    if (!q) return;
    if (collected.length >= count) return;
    const key = q.question.trim().toLowerCase();
    if (seen.has(key)) return;
    seen.add(key);
    collected.push(q);
  };

  // PASS 1 — Words (Target 2 questions). The user explicitly requested
  // 1-2 questions about Italian words learned today.
  const MAX_WORDS = 2;
  let wordsAdded = 0;
  for (let pass = 0; pass < 3 && wordsAdded < MAX_WORDS && collected.length < count; pass++) {
    const order = shuffleInPlace([...WORD_TEMPLATES.keys()], rng);
    for (const idx of order) {
      if (wordsAdded >= MAX_WORDS || collected.length >= count) break;
      const before = collected.length;
      tryAdd(WORD_TEMPLATES[idx](ctx));
      if (collected.length > before) wordsAdded++;
    }
  }

  // PASS 2 — Italian-culture wildcards (Target 4 questions, or more if few attractions).
  // The user explicitly requested 3-5 questions about general Italy
  // (flag, pizza Margherita, artists, geography). If there are very few
  // attractions today, fill the rest of the quiz with culture questions.
  const MAX_CULTURE = todaysAttractions.length < 2 ? (count - wordsAdded) : 4;
  let cultureAdded = 0;
  for (
    let i = 0;
    i < MAX_CULTURE * 4 && cultureAdded < MAX_CULTURE && collected.length < count;
    i++
  ) {
    const before = collected.length;
    tryAdd(tplItalianCulture(ctx));
    if (collected.length > before) cultureAdded++;
  }

  // PASS 3 — Curated Attraction Stories. When attractions on this day
  // have hand-authored `quizFacts`, those are the highest-quality
  // questions about the specific attractions.
  for (let i = 0; i < 10 && collected.length < count; i++) {
    tryAdd(tplAttractionStory(ctx));
  }

  // PASS 4 — fill remaining slots with the diverse generic attraction templates
  // (description, town, tag, region).
  const MAX_PASSES = 4;
  for (let pass = 0; pass < MAX_PASSES && collected.length < count; pass++) {
    const order = shuffleInPlace([...TEMPLATES.keys()], rng);
    for (const idx of order) {
      if (collected.length >= count) break;
      tryAdd(TEMPLATES[idx](ctx));
    }
  }

  // Finally, shuffle the collected questions so the different types
  // (words, culture, stories) are randomly mixed instead of clustered.
  shuffleInPlace(collected, rng);

  return {
    day: dayNumber,
    lang,
    questions: collected,
    // Marker timestamp 0 = "this is a fallback, not a real Gemini
    // generation". Anything reading the cache can distinguish if it
    // wants to (current orchestrator uses it to drive the banner).
    generatedAt: 0
  };
}
